config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      #get :status, to: 'api#status'
      mount_devise_token_auth_for 'User', at: 'users', controllers: {
        registrations: 'api/v1/registrations',
        sessions: 'api/v1/sessions',
        passwords: 'api/v1/passwords'
      }
      devise_scope :user do
        resource :user, only: %i[update show]
      end
      resources :acts
      resources :evaluations
      resources :cities
      resources :worktypes
      resources :statuses
      resources :polis_types
      resources :customers
    end
  end
  devise_for :users
  root 'home#index'
  get "/robots.txt", to: "robots#show"
  mount Sidekiq::Web => '/sidekiq'

  resources :prices, :ratings, :users, :worktypes, :otypes, :workshops, :repair_statuses
  
  namespace :user do
    resource :private_api_keys, only: :update
  end

  resources :actions do
  end

  match '/acts/operation', to: 'acts#book', via: 'get'
  match '/acts/bg', to: 'acts#book_generate', via: 'get'
  match '/evaluations/operation', to: 'evaluations#book', via: 'get'

  resources :charts, only: [] do
    collection do
      get 'acts_by_month'
      get 'acts_by_year'
      get 'specialist_acts_by_month'
      get 'specialist_book_by_month'
      get 'expert_exps_by_month'
      get 'expert_book_by_month'
      get 'all_acts_by_month'
      get 'all_bud_book_by_month'
      get 'all_customer_acts_by_month'
      get 'all_acts_per_day'
      get 'all_evaluations_per_day'
      get 'all_worktype_per_month'
      get 'all_evaluation_per_month'
      get 'all_evaluation_act_per_month'
      get 'all_act_per_month'
      get 'all_act_act_per_month'
    end
  end

  resources :acts do
    resources :audits, only: [ :index ]
    resources :comments, module: :acts
    delete :delete_images, on: :member
    delete :delete_calculations, on: :member
    delete :delete_additions, on: :member
    get 'clodup'
    collection do
      get 'download_xls', defaults: { format: 'xlsx' }
      get 'counts'
    end
  end

  resources :evaluations do
    resources :comments, module: :evaluations
    delete :delete_images, on: :member
    delete :delete_additions, on: :member
    get 'clodup'
    collection do
      get 'download_xls', defaults: { format: 'xlsx' }
    end
  end

  resources :discussions do
    resources :comments, module: :discussions
  end
end

app/models/workshop.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: workshops
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  email      :string
#  tel        :string
#  address    :string
#  manager    :string
#  active     :boolean          default(TRUE), not null
#
class Workshop < ApplicationRecord
  has_many :workshoplands
  has_many :cities, through: :workshoplands
  belongs_to :user

  def self.ransackable_attributes(auth_object = nil)
    ["active", "address", "created_at", "email", "id", "manager", "name", "tel", "updated_at", "user_id"]
  end

end

app/controllers/workshops_controller.rb
# frozen_string_literal: true

class WorkshopsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_workshop, only: %i[show edit update destroy]

  # GET /workshops
  # GET /workshops.json
  def index
    # @workshops = Workshop.all
    @q = policy_scope(Workshop).ransack(params[:q])
    @q.sorts = 'id asc' if @q.sorts.empty?
    @workshops = @q.result(distinct: true)
  end

  # GET /workshops/1
  # GET /workshops/1.json
  def show
    authorize @workshop
  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
    authorize @workshop
  end

  # GET /workshops/1/edit
  def edit
    authorize @workshop
  end

  # POST /workshops
  # POST /workshops.json
  def create
    
    @workshop = Workshop.new(workshop_params)
    authorize @workshop

    respond_to do |format|
      if @workshop.save
        format.html do
          redirect_to @workshop, notice: 'Workshop was successfully created.'
        end
        format.json { render :show, status: :created, location: @workshop }
      else
        format.html { render :new }
        format.json do
          render json: @workshop.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    authorize @workshop
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html do
          redirect_to @workshop, notice: 'Workshop was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @workshop }
      else
        format.html { render :edit }
        format.json do
          render json: @workshop.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    authorize @workshop
    @workshop.destroy
    respond_to do |format|
      format.html do
        redirect_to workshops_url, notice: 'Workshop was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_workshop
    @workshop = Workshop.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def workshop_params
    params.require(:workshop).permit(:user_id,
    :address,
    :tel,
    :manager,
    :email,
    :name,
    city_ids: [],
    )
  end
end

app/views/workshops/_form.html.haml
= simple_form_for @workshop, wrapper_mappings: {boolean: :custom_boolean, check_boxes: :custom_collection }  do |f|

  - if @workshop.errors.any?
    #error_explanation
      %h2= "#{pluralize(@workshop.errors.count, "error")} prohibited this workshope from being saved:"
      %ul
        - @workshop.errors.full_messages.each do |message|
          %li= message
  .form-row
    .col
      = f.input :name, :label => 'Название'
      = f.input :address, :label => 'Адрес'
      = f.input :tel, :label => 'Телефон'
      = f.input :manager, :label => 'Контактное лицо'
      = f.input :email, :label => 'Email'
      
    .col
      = f.association :user, collection: User.where(active: '1').order('name ASC'), :hint => "User", :label => 'Пользователь'
      = f.association :cities

     
  .form_actions
    = f.submit nil, :class => 'btn btn-primary', :value => "Сохранить"
    = link_to t('.cancel', :default => t("Отмена")), workshops_path, :class => 'btn btn-outline-secondary'

app/views/workshops/edit.html.haml
.card
  .card-header
    %h1.display-4
      СТО # #{@workshop.id}
  .card-body
    = render 'form'

app/views/workshops/index.html.haml
.card
  .card-header
    .row.align-items-center
      .col
        %h1.display-4 СТО
      .col
        .btn-group.float-right{"aria-label" => "...", :role => "group"}
          = link_to new_workshop_path,
            :class => "btn btn-primary" do
            %i.bi.bi-plus-square
            Добавить СТО
  .card-body
    = search_form_for @q do |f|
      %table.table
        %thead
          %tr
            %th= sort_link @q, :id, 'id'
            %th= sort_link @q, :name, 'Название'
            %th= sort_link @q, :user_id, 'Закрепленный пользователь'
            %th Территория


        %tbody
          - @workshops.each do |workshop|
            %tr{"data-controller" => "row-link", "data-row-link-href" => url_for(workshop)}
              %td{ "data-action" => "click->row-link#click"} 
                =workshop.id
              %td{ "data-action" => "click->row-link#click"}
                = workshop.name
              %td{ "data-action" => "click->row-link#click"}
                = workshop.user.try(:name)
              %td{ "data-action" => "click->row-link#click"}
                - workshop.cities.each do |cities|
                  %span.badge.badge-secondary
                    = cities.name

app/views/workshops/new.html.haml
.card
  .card-header
    %h1.display-4
      Новая СТО
  .card-body
    = render 'form'
    

app/views/workshops/show.html.haml
%p#notice= notice
.card
  .card-header
    %h1.display-4
      СТО # #{@workshop.id}
  .card-body
    %p
      %b Название:
      = @workshop.name
    %p
      %b Адрес:
      = @workshop.address
    %p
      %b Телефон:
      = @workshop.tel
    %p
      %b Контактное лицо:
      = @workshop.manager
    %p
      %b Email:
      = @workshop.email
    %p
      %b Города покрытия:  
      - @workshop.cities.each do |cities|
        %span.badge.badge-secondary
          = cities.name
    %p
      %b Пользователь:
      = @workshop.user.try(:name)

    .form_actions
      = link_to 'Назад', workshops_path, :class => 'btn btn-primary '
      = link_to 'Редактировать', edit_workshop_path(@workshop), :class => 'btn btn-outline-primary'
      = link_to 'Удалить', workshop_path(@workshop), :method => 'delete', data: {confirm: "Are you sure?"}, :class => 'btn btn-outline-danger'