config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      #get :status, to: 'api#status'
      mount_devise_token_auth_for 'User', at: 'users', controllers: {
        registrations: 'api/v1/registrations',
        sessions: 'api/v1/sessions',
        passwords: 'api/v1/passwords'
      }
      devise_scope :user do
        resource :user, only: %i[update show]
      end
      resources :acts
      resources :evaluations
      resources :cities
      resources :worktypes
      resources :statuses
      resources :polis_types
      resources :customers
    end
  end
  devise_for :users
  root 'home#index'
  get "/robots.txt", to: "robots#show"
  mount Sidekiq::Web => '/sidekiq'

  resources :prices, :ratings, :users, :worktypes, :otypes, :workshops, :repair_statuses
  
  namespace :user do
    resource :private_api_keys, only: :update
  end

  resources :actions do
  end

  match '/acts/operation', to: 'acts#book', via: 'get'
  match '/acts/bg', to: 'acts#book_generate', via: 'get'
  match '/evaluations/operation', to: 'evaluations#book', via: 'get'

  resources :charts, only: [] do
    collection do
      get 'acts_by_month'
      get 'acts_by_year'
      get 'specialist_acts_by_month'
      get 'specialist_book_by_month'
      get 'expert_exps_by_month'
      get 'expert_book_by_month'
      get 'all_acts_by_month'
      get 'all_bud_book_by_month'
      get 'all_customer_acts_by_month'
      get 'all_acts_per_day'
      get 'all_evaluations_per_day'
      get 'all_worktype_per_month'
      get 'all_evaluation_per_month'
      get 'all_evaluation_act_per_month'
      get 'all_act_per_month'
      get 'all_act_act_per_month'
    end
  end

  resources :acts do
    resources :audits, only: [ :index ]
    resources :comments, module: :acts
    delete :delete_images, on: :member
    delete :delete_calculations, on: :member
    delete :delete_additions, on: :member
    get 'clodup'
    collection do
      get 'download_xls', defaults: { format: 'xlsx' }
      get 'counts'
    end
  end

  resources :evaluations do
    resources :comments, module: :evaluations
    delete :delete_images, on: :member
    delete :delete_additions, on: :member
    get 'clodup'
    collection do
      get 'download_xls', defaults: { format: 'xlsx' }
    end
  end

  resources :discussions do
    resources :comments, module: :discussions
  end
end

app/models/discussion.rb
# == Schema Information
#
# Table name: discussions
#
#  id         :bigint           not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Discussion < ApplicationRecord
  has_many :comments, as: :commentable
end

app/controllers/discussions/comments_controller.rb
class Discussions::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Discussion.find(params[:discussion_id])
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: %i[show edit update destroy]

  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.all
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show; end

  # GET /discussions/new
  def new
    @discussion = Discussion.new
  end

  # GET /discussions/1/edit
  def edit; end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = Discussion.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html do
          redirect_to @discussion,
                      notice: 'Discussion was successfully created.'
        end
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new }
        format.json do
          render json: @discussion.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html do
          redirect_to @discussion,
                      notice: 'Discussion was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit }
        format.json do
          render json: @discussion.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html do
        redirect_to discussions_url,
                    notice: 'Discussion was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_discussion
    @discussion = Discussion.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def discussion_params
    params.require(:discussion).permit(:title)
  end
end

app/views/discussions/_form.html.haml
= form_with(model: discussion, local: true) do |form|
  - if discussion.errors.any?
    #error_explanation
      %h2
        = pluralize(discussion.errors.count, "error")
        prohibited this discussion from being saved:
      %ul
        - discussion.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label :title
    = form.text_field :title, class: 'form-control'
  .form-group
    - if discussion.persisted?
      .float-end
        = link_to 'Destroy', discussion, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' }
    = form.submit class: 'btn btn-primary'
    - if discussion.persisted?
      = link_to "Cancel", discussion, class: "btn btn-link"
    - else
      = link_to "Cancel", discussions_path, class: "btn btn-link"

app/views/discussions/edit.html.haml
%h1 Edit Discussion
= render 'form', discussion: @discussion

app/views/discussions/index.html.haml
.card
  .card-header
    .row
      .col-sm-6
        %h1 Обсуждения
      .col-sm-6.text-right
        = link_to new_discussion_path, class: 'btn btn-primary' do
          Новое обсуждение
    .card-body
      .table-responsive
        %table.table.table-striped.table-bordered.table-hover
          %thead
            %tr
              %th Тема
              %th
          %tbody
            - @discussions.each do |discussion|
              = content_tag :tr, id: dom_id(discussion), class: dom_class(discussion) do
                %td= discussion.title
                %td= link_to 'Show', discussion

app/views/discussions/new.html.haml
%h1 New discussion
= render 'form', discussion: @discussion

app/views/discussions/show.html.haml
.page-header
  = link_to discussions_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    All Discussions
  = link_to edit_discussion_path(@discussion), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show discussion
%dl.dl-horizontal
  %dt Title:
  %dd= @discussion.title
%h3 Comments
#comments
  = render partial: "comments/form", locals: { commentable: @discussion }
  = render @discussion.comments.where(parent_id: nil), max_nesting: 2