config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      #get :status, to: 'api#status'
      mount_devise_token_auth_for 'User', at: 'users', controllers: {
        registrations: 'api/v1/registrations',
        sessions: 'api/v1/sessions',
        passwords: 'api/v1/passwords'
      }
      devise_scope :user do
        resource :user, only: %i[update show]
      end
      resources :acts
      resources :evaluations
      resources :cities
      resources :worktypes
      resources :statuses
      resources :polis_types
      resources :customers
    end
  end
  devise_for :users
  root 'home#index'
  get "/robots.txt", to: "robots#show"
  mount Sidekiq::Web => '/sidekiq'

  resources :prices, :ratings, :users, :worktypes, :otypes, :workshops, :repair_statuses
  
  namespace :user do
    resource :private_api_keys, only: :update
  end

  resources :actions do
  end

  match '/acts/operation', to: 'acts#book', via: 'get'
  match '/acts/bg', to: 'acts#book_generate', via: 'get'
  match '/evaluations/operation', to: 'evaluations#book', via: 'get'

  resources :charts, only: [] do
    collection do
      get 'acts_by_month'
      get 'acts_by_year'
      get 'specialist_acts_by_month'
      get 'specialist_book_by_month'
      get 'expert_exps_by_month'
      get 'expert_book_by_month'
      get 'all_acts_by_month'
      get 'all_bud_book_by_month'
      get 'all_customer_acts_by_month'
      get 'all_acts_per_day'
      get 'all_evaluations_per_day'
      get 'all_worktype_per_month'
      get 'all_evaluation_per_month'
      get 'all_evaluation_act_per_month'
      get 'all_act_per_month'
      get 'all_act_act_per_month'
    end
  end

  resources :acts do
    resources :audits, only: [ :index ]
    resources :comments, module: :acts
    delete :delete_images, on: :member
    delete :delete_calculations, on: :member
    delete :delete_additions, on: :member
    get 'clodup'
    collection do
      get 'download_xls', defaults: { format: 'xlsx' }
      get 'counts'
    end
  end

  resources :evaluations do
    resources :comments, module: :evaluations
    delete :delete_images, on: :member
    delete :delete_additions, on: :member
    get 'clodup'
    collection do
      get 'download_xls', defaults: { format: 'xlsx' }
    end
  end

  resources :discussions do
    resources :comments, module: :discussions
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  protect_from_forgery with: :exception
  
  skip_after_action :verify_policy_scoped

  def index
    @summ_all_day = (Act.where('created_at > ?', 1.months.ago).sum(:summ_act) + Act.where('created_at > ?', 1.months.ago).sum(:summ_exp) + Act.where('created_at > ?', 1.months.ago).sum(:summ_viezd)) / 30
    @summ_alle_day = (Evaluation.where('created_at > ?', 1.months.ago).sum(:summ_act) + Evaluation.where('created_at > ?', 1.months.ago).sum(:summ_exp) + Evaluation.where('created_at > ?', 1.months.ago).sum(:summ_viezd)) / 30
  end
end

app/views/home/denied.html.haml
%br/
%h3 Пожалуйста авторизируйтесь для продолжения работы
%p

app/views/home/index.html.haml
- if user_signed_in? 
  .container-fluid
    .row.py-2
      .col-md-4.py-1
        .card.border-light
          .card-body
            %h5.card-title База данных
            %h6.card-subtitle.mb-2.text-muted 
              = current_user.roles.map(&:name).join(', ')
            %p.card-text 
            %h1
              = current_user.name
              %small.text-muted
            %p      
            = link_to '+экспертиза', new_act_path, :class => "card-link"
            = link_to '+оценка', new_evaluation_path, :class => "card-link"
      .col-md-4.py-1
        .card.border-light
          .card-body
            %h5.card-title 
              = 'Количество'
              = 'дел'
            %h6.card-subtitle.mb-2.text-muted всего
            %p.card-text 
            %h1
              = policy_scope(Act).count
              %small.text-muted / шт
            %p
            = link_to '+экспертиза', new_act_path, :class => "card-link"
            = link_to '+оценка', new_evaluation_path, :class => "card-link"

      .col-md-4.py-1
        .card.border-light
          .card-body
            %h5.card-title Экспертиза
            %h6.card-subtitle.mb-2.text-muted в работе
            %p.card-text 
            %h1
              = policy_scope(Act).inthework.count
              %small.text-muted / шт
            %p
            = link_to '+экспертиза', new_act_path, :class => "card-link"
    
    .row.py-2
      .col-md-4.py-1
        .card.border-light
          .card-body
            %h5.card-title Оценка
            %h6.card-subtitle.mb-2.text-muted в работе
            %p.card-text 
            %h1
              = policy_scope(Evaluation).inthework.count
              %small.text-muted / шт
            %p
            = link_to '+оценка', new_evaluation_path, :class => "card-link"
    
    - if current_user.specialist?
      .row.my-2
        .col-md-6.py-1
          .card
            .card-body
              %h5.card-title Мои акты
              %h6.card-subtitle.mb-2.text-muted статистика количества
              %p.card-text 
              %p
                = column_chart specialist_acts_by_month_charts_url
        .col-md-6.py-1
          .card
            .card-body
              %h5.card-title Мои обороты по актам
              %h6.card-subtitle.mb-2.text-muted статистика книги
              %p.card-text 
              
              %p
                = line_chart specialist_book_by_month_charts_url
    
    - if current_user.expert?
      .row.my-2
        .col-md-6.py-1
          .card
            .card-body
              %h5.card-title Мои экспертизы
              %h6.card-subtitle.mb-2.text-muted статистика количества
              %p.card-text 
              %p
                = column_chart expert_exps_by_month_charts_url
        .col-md-6.py-1
          .card
            .card-body
              %h5.card-title Мои обороты по экспертизам
              %h6.card-subtitle.mb-2.text-muted статистика книги
              %p.card-text 
              
              %p
                = line_chart expert_book_by_month_charts_url
    
    - if current_user.admin?
      .row.my-2
        .col-md-6.py-1
          .card
            .card-body
              %h5.card-title Всего дел в месяц
              %h6.card-subtitle.mb-2.text-muted статистика количества
              %p.card-text 
              %p
                = line_chart all_acts_by_month_charts_url
        .col-md-6.py-1
          .card
            .card-body
              %h5.card-title Обороты по СОДФУ
              %h6.card-subtitle.mb-2.text-muted статистика книги
              %p.card-text 
              
              %p
                = column_chart all_bud_book_by_month_charts_url
      .row.my-2
        .col-md-6.py-1
          .card
            .card-body
              %h5.card-title Актов в день
              %h6.card-subtitle.mb-2.text-muted статистика количества
              %p.card-text 
              %p
                = column_chart all_acts_per_day_charts_url
        .col-md-6.py-1
          .card
            .card-body
              %h5.card-title Оценок в день
              %h6.card-subtitle.mb-2.text-muted статистика количества
              %p.card-text 
              %p
                = column_chart all_evaluations_per_day_charts_url
      .row.my-2
        .col-md-6.py-1
          .card
            .card-body
              %h5.card-title Оценка сумма за расчеты
              %h6.card-subtitle.mb-2.text-muted статистика количества
              %p.card-text 
              %p
                = column_chart all_evaluation_per_month_charts_url
        .col-md-6.py-1
          .card
            .card-body
              %h5.card-title Оценка сумма за акты
              %h6.card-subtitle.mb-2.text-muted статистика количества
              %p.card-text 
              %p
                = column_chart all_evaluation_act_per_month_charts_url
      
      .row.my-2
        .col-md-6.py-1
          .card
            .card-body
              %h5.card-title Экспертизы сумма за расчеты
              %h6.card-subtitle.mb-2.text-muted статистика количества
              %p.card-text 
              %p
                = column_chart all_act_per_month_charts_url
        .col-md-6.py-1
          .card
            .card-body
              %h5.card-title Экспертизы сумма за акты
              %h6.card-subtitle.mb-2.text-muted статистика количества
              %p.card-text 
              %p
                = column_chart all_act_act_per_month_charts_url
    
    - if current_user.customer?
      .row.my-2
        .col-md-6.py-1
          .card
            .card-body
              %h5.card-title Всего дел в месяц
              %h6.card-subtitle.mb-2.text-muted статистика количества
              %p.card-text 
              %p
                = line_chart all_customer_acts_by_month_charts_url
    
    = @summ_all_day
    = @summ_alle_day