config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      #get :status, to: 'api#status'
      mount_devise_token_auth_for 'User', at: 'users', controllers: {
        registrations: 'api/v1/registrations',
        sessions: 'api/v1/sessions',
        passwords: 'api/v1/passwords'
      }
      devise_scope :user do
        resource :user, only: %i[update show]
      end
      resources :acts
      resources :evaluations
      resources :cities
      resources :worktypes
      resources :statuses
      resources :polis_types
      resources :customers
    end
  end
  devise_for :users
  root 'home#index'
  get "/robots.txt", to: "robots#show"
  mount Sidekiq::Web => '/sidekiq'

  resources :prices, :ratings, :users, :worktypes, :otypes, :workshops, :repair_statuses
  
  namespace :user do
    resource :private_api_keys, only: :update
  end

  resources :actions do
  end

  match '/acts/operation', to: 'acts#book', via: 'get'
  match '/acts/bg', to: 'acts#book_generate', via: 'get'
  match '/evaluations/operation', to: 'evaluations#book', via: 'get'

  resources :charts, only: [] do
    collection do
      get 'acts_by_month'
      get 'acts_by_year'
      get 'specialist_acts_by_month'
      get 'specialist_book_by_month'
      get 'expert_exps_by_month'
      get 'expert_book_by_month'
      get 'all_acts_by_month'
      get 'all_bud_book_by_month'
      get 'all_customer_acts_by_month'
      get 'all_acts_per_day'
      get 'all_evaluations_per_day'
      get 'all_worktype_per_month'
      get 'all_evaluation_per_month'
      get 'all_evaluation_act_per_month'
      get 'all_act_per_month'
      get 'all_act_act_per_month'
    end
  end

  resources :acts do
    resources :audits, only: [ :index ]
    resources :comments, module: :acts
    delete :delete_images, on: :member
    delete :delete_calculations, on: :member
    delete :delete_additions, on: :member
    get 'clodup'
    collection do
      get 'download_xls', defaults: { format: 'xlsx' }
      get 'counts'
    end
  end

  resources :evaluations do
    resources :comments, module: :evaluations
    delete :delete_images, on: :member
    delete :delete_additions, on: :member
    get 'clodup'
    collection do
      get 'download_xls', defaults: { format: 'xlsx' }
    end
  end

  resources :discussions do
    resources :comments, module: :discussions
  end
end

app/models/price.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: prices
#
#  id          :bigint           not null, primary key
#  user_id     :bigint
#  worktype_id :bigint
#  cost        :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Price < ApplicationRecord
  belongs_to :user
  belongs_to :worktype
  validates :cost, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["cost", "created_at", "id", "updated_at", "user_id", "worktype_id"]
  end
  
end

app/controllers/prices_controller.rb
# frozen_string_literal: true

class PricesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_price, only: %i[show edit update destroy]

  # GET /prices
  # GET /prices.json
  def index
    # @prices = Price.all
    @q = policy_scope(Price).ransack(params[:q])
    @q.sorts = 'id asc' if @q.sorts.empty?
    @prices = @q.result(distinct: true)
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
    authorize @price
  end

  # GET /prices/new
  def new
    @price = Price.new
    authorize @price
  end

  # GET /prices/1/edit
  def edit
    authorize @price
  end

  # POST /prices
  # POST /prices.json
  def create
    
    @price = Price.new(price_params)
    authorize @price

    respond_to do |format|
      if @price.save
        format.html do
          redirect_to @price, notice: 'Price was successfully created.'
        end
        format.json { render :show, status: :created, location: @price }
      else
        format.html { render :new }
        format.json do
          render json: @price.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    authorize @price
    respond_to do |format|
      if @price.update(price_params)
        format.html do
          redirect_to @price, notice: 'Price was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @price }
      else
        format.html { render :edit }
        format.json do
          render json: @price.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    authorize @price
    @price.destroy
    respond_to do |format|
      format.html do
        redirect_to prices_url, notice: 'Price was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_price
    @price = Price.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def price_params
    params.require(:price).permit(:worktype_id, :user_id, :cost)
  end
end

app/views/prices/_form.html.haml
= simple_form_for @price, wrapper_mappings: {boolean: :custom_boolean, check_boxes: :custom_collection }  do |f|

  - if @price.errors.any?
    #error_explanation
      %h2= "#{pluralize(@price.errors.count, "error")} prohibited this price from being saved:"
      %ul
        - @price.errors.full_messages.each do |message|
          %li= message
  .form-row
    .col
      = f.association :user, collection: User.customer.where(active: '1').order('name ASC'), :hint => "Заказчик или страховая компания", :label => 'Заказчик'
    .col
      = f.association :worktype, :as => :radio_buttons, :label => 'Тип дела'
    .col
      = f.input :cost, :label => 'Цена'
     
  .form_actions
    = f.submit nil, :class => 'btn btn-primary', :value => "Сохранить"
    = link_to t('.cancel', :default => t("Отмена")), prices_path, :class => 'btn btn-outline-secondary'

app/views/prices/edit.html.haml
.card
  .card-header
    %h1.display-4
      Цена # #{@price.id}
  .card-body
    = render 'form'

app/views/prices/index.html.haml
.card
  .card-header
    .row.align-items-center
      .col
        %h1.display-4 Таблица цен
      .col
        .btn-group.float-end{"aria-label" => "...", :role => "group"}
          = link_to new_price_path,
            :class => "btn btn-primary" do
            %i.fas.fa-plus
            Добавить цену
  .card-body
    = search_form_for @q do |f|
      %table.table
        %thead
          %tr
            %th= sort_link @q, :id, 'id'
            %th= sort_link @q, :user_id, 'Заказчик'
            %th= sort_link @q, :worktype_id, 'Тип работы'
            %th Цена
            %th
            %th
            %th
        %tbody
          - @prices.each do |price|
            %tr{"data-controller" => "row-link", "data-row-link-href" => url_for(price)}
              %td{ "data-action" => "click->row-link#click"} 
                =price.id
              %td{ "data-action" => "click->row-link#click"}
                = price.user.name
              %td{ "data-action" => "click->row-link#click"}
                = price.worktype.name
              %td{ "data-action" => "click->row-link#click"}
                = price.cost
              %td= link_to 'Редактировать', edit_price_path(price)
              %td= link_to 'Удалить', price, method: :delete, data: { confirm: 'Are you sure?' }

app/views/prices/new.html.haml
.card
  .card-header
    %h1.display-4
      Новая цена
  .card-body
    = render 'form'
    

app/views/prices/show.html.haml
%p#notice= notice
.card
  .card-header
    %h1.display-4
      Цена # #{@price.id}
  .card-body
    %p
      %b Заказчик:
      = @price.user.name
    %p
      %b Тип работы:
      = @price.worktype.name
    %p
      %b Цена:
      = @price.cost
    .form_actions
      = link_to 'Назад', prices_path, :class => 'btn btn-primary '
      = link_to 'Редактировать', edit_price_path(@price), :class => 'btn btn-outline-primary'